[package]
name = "hedgewars-server"
version = "0.0.1"
authors = [ "Andrey Korotaev <a.korotaev@hedgewars.org>" ]
build = "build.rs"

[dependencies]
rand = "0.3"
mio = "0.6"
slab = "0.3"
netbuf = "0.3.8"
lalrpop-util = "0.12.4"

[build-dependencies]
lalrpop = "0.12.4"
